from llm_sdk import Small_LLM_Model
from src.validator import tokens_validator
from typing import Any


def generate_value(
        type_parameter: str,
        model: Small_LLM_Model,
        input_ids_list: list[int],
        generated_tokens: list[int],
        valid_ids: list[int]
) -> Any:
    """ Generate and extract the parameter value from the LLM based
        on its expected type.
        __getitem__ - Uses fast C-level native indexing instead of a slow
        lambda. When calling my_list[1], Python internally executes:
        my_list.__getitem__(1).
        Using __getitem__ directly allows us to avoid the slowness of a
        lambda function.
    Args:
        type_parameter (str): Expected parameter type ('number' or 'string').
        model (Small_LLM_Model): The LLM wrapper instance used for decoding
        and logits.
        input_ids_list (list[int]): Accumulated context token IDs.
        generated_tokens (list[int]): Tokens generated specifically for this
        response.
    Returns:
        Any: The extracted value cast to float/int for numbers, or str for
        strings.
    """
    val_tokens = []

    for step in range(15):
        logits = model.get_logits_from_input_ids(input_ids_list)

        if type_parameter == "number":
            best_token_id = max(valid_ids, key=logits.__getitem__)
            clean_word = model.decode([best_token_id]).strip()

        elif type_parameter == "string":
            best_token_id = logits.index(max(logits))
            clean_word = model.decode([best_token_id]).strip()
            if '"' in clean_word:
                break

        if clean_word in [",", "}"]:
            break

        input_ids_list.append(best_token_id)
        generated_tokens.append(best_token_id)
        val_tokens.append(best_token_id)

    # if the type_parameter expected is "number"
    # -> cast to "float" or "int" bf return
    raw_val = model.decode(val_tokens).strip()
    if type_parameter == "number":
        try:
            return float(raw_val) if "." in raw_val else int(raw_val)
        except ValueError:
            return 0.0

    return raw_val


def force_string(
        target_string: str,
        model: Small_LLM_Model,
        input_ids_list: list[int],
        generated_tokens: list[int]
) -> None:
    """ Force specific target tokens into the context and generated token
        list.
    Args:
        target_string (str): The exact text sequence to inject.
        model (Small_LLM_Model): The LLM wrapper instance used to encode the
        string.
        input_ids_list (list[int]): Accumulated context token IDs to update.
        generated_tokens (list[int]): List of generated token IDs to update.
    """
    target_tokens = model.encode(target_string).tolist()[0]

    input_ids_list.extend(target_tokens)
    generated_tokens.extend(target_tokens)


def nudger(
        generated_tokens: list[int],
        encoded_functions: list[list[int]]
) -> list[int]:
    """ Manage Finite State Machine (FSM) states for Grammar-Guided
        Generation.
        Tracks the current state of the generated sequence and determines
        the syntactically valid subset of next token IDs from candidate
        function signatures to enforce schema compliance.
    Args:
        generated_tokens (list[int]): Token sequence generated so far.
        encoded_functions (list[list[int]]): Pre-encoded token sequences
        of valid function prefixes.
    Returns:
        list[int]: List of allowed token IDs for the current generation step.
    """
    step = len(generated_tokens)
    allowed_ids = []

    # if func_tokens[:step] == generated_tokens:
    # -> builds the available next steps based on what is already written
    for func_tokens in encoded_functions:
        if func_tokens[:step] == generated_tokens:
            if step < len(func_tokens):
                allowed_ids.append(func_tokens[step])
    return allowed_ids


def constrained_decoder(
        model: Small_LLM_Model,
        input_ids_list: list[int],
        functions_json: list[dict[str, Any]],
        user_question: str,
        valid_ids: list[int]
) -> dict[str, Any]:
    """ Perform constrained decoding to pick a function and extract valid
        parameters. Uses token masking against candidate function definitions
        to ensure only schema-compliant function calls are generated by the
        LLM.
    Args:
        model (Small_LLM_Model): The LLM wrapper instance.
        input_ids_list (list[int]): Initial prompt token IDs.
        functions_json (list[dict]): List of available function definitions
        with schemas.
        user_question (str): The original natural-language user query.
    Returns:
        dict: Structured function call containing
        'prompt', 'name', and 'parameters'.
    """
    functions_name = [f['name'] for f in functions_json]
    encoded_functions = []
    for name in functions_name:
        full_string = '"name": "' + name + '", "parameters": {'
        func_tokens = model.encode(full_string).tolist()[0]
        encoded_functions.append(func_tokens)

    generated_tokens: list[int] = []

    for step in range(20):
        logits = model.get_logits_from_input_ids(input_ids_list)
        allowed_ids = nudger(generated_tokens, encoded_functions)

        if not allowed_ids or allowed_ids == [None]:
            break

        #for i in range(len(logits)):
        #    if i not in allowed_ids:
        #        logits[i] = float('-inf')

        best_token_id = max(allowed_ids, key=lambda i: logits[i])

        input_ids_list.append(best_token_id)
        generated_tokens.append(best_token_id)

    final_text = model.decode(generated_tokens)

    # function name chosen
    after_prefix = final_text.split('"name": "')[1]
    function_chosen = after_prefix.split('"')[0]
    extracted_params = {}
    parameters = {}
    for func in functions_json:
        if func["name"] == function_chosen:
            parameters = func.get("parameters", {})
            break
    parameters_name = list(parameters.keys())
    for index, name in enumerate(parameters_name):
        target_string = '"' + name + '": '
        force_string(target_string, model, input_ids_list, generated_tokens)

        type_parameter = parameters[name]["type"]
        if type_parameter == "number":
            value = generate_value(
                type_parameter, model,
                input_ids_list, generated_tokens,
                valid_ids
            )
            extracted_params[name] = value
        elif type_parameter == "string":
            force_string('"', model, input_ids_list, generated_tokens)
            value = generate_value(
                type_parameter, model,
                input_ids_list, generated_tokens,
                valid_ids
            )
            extracted_params[name] = value
            force_string('"', model, input_ids_list, generated_tokens)

        is_last = (index == len(parameters_name) - 1)
        if not is_last:
            force_string(', ', model, input_ids_list, generated_tokens)

    force_string('}', model, input_ids_list, generated_tokens)

    return {
        "prompt": user_question,
        "name": function_chosen,
        "parameters": extracted_params
    }


def llm_interaction(
        json_input: list[dict[str, str]],
        functions_json: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """ Format prompts, process queries with the LLM, and collect function
        call results. Formats function signatures by extracting parameter
        names and types from `func.get('parameters', {}).items()` using a
        list comprehension: `[f"{p_name}: {p_info['type']}"
        for p_name, p_info in func.get('parameters', {}).items()]`.
        Constructs a ChatML prompt for each query and runs constrained
        decoding.
    Args:
        test_quest_json (list[dict[str, str]]): List of test objects
        containing natural language prompts.
        functions_json (list[dict]): List of available function definitions
        and metadata.
    Returns:
        list[dict]: List of structured function call result dictionaries.
    """
    model = Small_LLM_Model()
    valid_ids = tokens_validator(model)

    tools_text = "Available functions:\n"
    for func in functions_json:
        params_desc = ", ".join([
            f"{p_name}: {p_info['type']}"
            for p_name, p_info in func.get("parameters", {}).items()
        ])
        tools_text += (
            f"- {func['name']}({params_desc}): {func['description']}\n"
        )

    all_results = []
    for quest in json_input:
        user_question = quest["prompt"]
        prompt = (
            "<|im_start|>system\n"
            "You are a helpful assistant. "
            "Select the correct tool and extract "
            "its parameters to answer the user request.\n"
            f"{tools_text}<|im_end|>\n"
            f"<|im_start|>user\n{user_question}<|im_end|>\n"
            "<|im_start|>assistant\n{"
        )

        encoded_tensor = model.encode(prompt)
        input_ids_list = encoded_tensor.tolist()[0]

        # Constrained Decoding function:
        result_item = constrained_decoder(
            model,
            input_ids_list,
            functions_json,
            user_question,
            valid_ids
        )
        all_results.append(result_item)

    return all_results
